from tkinter import *

item1 = StringVar()
Checkbuton(master, text="Water", variable=item).grid(row=0, sticky=W)
item2 = StringVar()
Checkbuton(master, text="Rope", variable=item).grid(row=1, sticky=W)
item3 = StringVar()
Checkbuton(master, text="Tent", variable=item).grid(row=2, sticky=W)
item4 = StringVar()
Checkbuton(master, text="Sleeping Bag", variable=item).grid(row=3, sticky=W)
item5 = StringVar()
Checkbuton(master, text="Matches", variable=item).grid(row=4, sticky=W)
item6 = StringVar()
Checkbuton(master, text="Tarp", variable=item).grid(row=5, sticky=W)
item7 = StringVar()
Checkbuton(master, text="Tinder", variable=item).grid(row=6, sticky=W)
item8 = StringVar()
Checkbuton(master, text="Hatchet", variable=item).grid(row=7, sticky=W)
item10 = StringVar()
Checkbuton(master, text="Striker", variable=item).grid(row=8, sticky=W)
item11 = StringVar()
Checkbuton(master, text="Paracord/String", variable=item).grid(row=9, sticky=W)
item12 = StringVar()
Checkbuton(master, text="Stake", variable=item).grid(row=10, sticky=W)
item13 =StringVar()
Checkbuton(master, text="Flashlight/Torch", variable=item).grid(row=11, sticky=W)
item14 = StringVar()
Checkbuton(master, text="Batteries", variable=item).grid(row=12, sticky=W)
item15 = StringVar()
Checkbuton(master, text="Lantern", variable=item).grid(row=13, sticky=W)
item16 =StringVar()
Checkbuton(master, text="Lantern Fuel", variable=item).grid(row=14, sticky=W)

Button(master, text='Finalize List')

def checklist(Frame):
   print("Water: %d,) 