from tkinter import *
checklist_inv = Tk()

def check_item():
   print("Water: %d, Rope: %d, Tent: %d, Sleeping Bag: %d, Matches: %d, Tarp: %d, Tinder: %d, Hatchet: %d, Striker: %d, Paracord/String: %d, Stakes: %d, Flashlight/Torch: %d, Batteries: %d, Lantern: %d, Lantern Fuel: %d" % (item1.get(), item2.get(), item3.get(), item4.get(), item5.get(), item6.get(), item7.get(), item8.get(), item9.get(), item10.get(), item11.get(), item12.get(), item13.get(), item14.get(), item15.get()))

Label(master, text="What are you packing?").grid(row=0, sticky=W)
item1 = IntVar()
Checkbuton(master, text="Water", variable=item1).grid(row=1, sticky=W)
item2 = IntVar()
Checkbuton(master, text="Rope", variable=item2).grid(row=2, sticky=W)
item3 = IntVar()
Checkbuton(master, text="Tent", variable=item3).grid(row=3, sticky=W)
item4 = IntVar()
Checkbuton(master, text="Sleeping Bag", variable=item4).grid(row=4, sticky=W)
item5 = IntVar()
Checkbuton(master, text="Matches", variable=item5).grid(row=5, sticky=W)
item6 = IntVar()
Checkbuton(master, text="Tarp", variable=item6).grid(row=6, sticky=W)
item7 = IntVar()
Checkbuton(master, text="Tinder", variable=item7).grid(row=7, sticky=W)
item8 = IntVar()
Checkbuton(master, text="Hatchet", variable=item8).grid(row=8, sticky=W)
item9 = IntVar()
Checkbuton(master, text="Striker", variable=item9).grid(row=9, sticky=W)
item10 = IntVar()
Checkbuton(master, text="Paracord/String", variable=item10).grid(row=10, sticky=W)
item11 = IntVar()
Checkbuton(master, text="Stakes", variable=item11).grid(row=11, sticky=W)
item12 = IntVar()
Checkbuton(master, text="Flashlight/Torch", variable=item12).grid(row=12, sticky=W)
item13 = IntVar()
Checkbuton(master, text="Batteries", variable=item13).grid(row=13, sticky=W)
item14 = IntVar()
Checkbuton(master, text="Lantern", variable=item14).grid(row=14, sticky=W)
item15 = IntVar()
Checkbuton(master, text="Lantern Fuel", variable=item15).grid(row=15, sticky=W)
Button(master, text='Finalize List')
mainloop()